name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:

  build:

    name: Build Image

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # - run: echo ::set-env name=IMAGE_TAG::${GITHUB_REF:10}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: github.event_name != 'release'
        uses: docker/build-push-action@v3

      - name: Release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner	}}/jmeter:latest
            ghcr.io/${{ github.repository_owner	}}/jmeter:${{ github.event.release.tag_name }}
